DROP DATABASE IF EXISTS car_rental_service;
DROP USER IF EXISTS `root`@`%`;
CREATE DATABASE IF NOT EXISTS car_rental_service CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `root`@`%` IDENTIFIED WITH mysql_native_password BY '12345678';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `car_rental_service`.* TO `root`@`%`;